backend:
  name: git-gateway
  branch: main

publish_mode  : editorial_workflow

media_folder: "src/assets"
public_folder: "/assets"

collections:
  - name:   "blog"
    label:  "Blog"
    folder: "src/content/blog"
    create: true 
    slug:   "b-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "@layouts/BlogPost.astro"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "publication", widget: "datetime"}
      - {label: "Hero Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {name: "categories", label: "Categories", widget: "categories", separator: __}